<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Country::create(['codigo' => 'AF', 'country' => 'Afganistán']);
        Country::create(['codigo' => 'AL', 'country' => 'Albania']);
        Country::create(['codigo' => 'DE', 'country' => 'Alemania']);
        Country::create(['codigo' => 'DZ', 'country' => 'Argelia']);
        Country::create(['codigo' => 'AD', 'country' => 'Andorra']);
        Country::create(['codigo' => 'AO', 'country' => 'Angola']);
        Country::create(['codigo' => 'AI', 'country' => 'Anguila']);
        Country::create(['codigo' => 'AQ', 'country' => 'Antártida']);
        Country::create(['codigo' => 'AG', 'country' => 'Antigua y Barbuda']);
        Country::create(['codigo' => 'AN', 'country' => 'Antillas Neerlandesa s']);
        Country::create(['codigo' => 'SA', 'country' => 'Arabia Saudita']);
        Country::create(['codigo' => 'AR', 'country' => 'Argentina']);
        Country::create(['codigo' => 'AM', 'country' => 'Armenia']);
        Country::create(['codigo' => 'AW', 'country' => 'Aruba']);
        Country::create(['codigo' => 'AU', 'country' => 'Australia']);
        Country::create(['codigo' => 'AT', 'country' => 'Austria']);
        Country::create(['codigo' => 'AZ', 'country' => 'Azerbaiyán']);
        Country::create(['codigo' => 'BE', 'country' => 'Bélgica']);
        Country::create(['codigo' => 'BS', 'country' => 'Bahamas']);
        Country::create(['codigo' => 'BH', 'country' => 'Bahréin']);
        Country::create(['codigo' => 'BD', 'country' => 'Bangladesh']);
        Country::create(['codigo' => 'BB', 'country' => 'Barbados']);
        Country::create(['codigo' => 'BZ', 'country' => 'Belice']);
        Country::create(['codigo' => 'BT', 'country' => 'Bután']);
        Country::create(['codigo' => 'BY', 'country' => 'Bielorrusia']);
        Country::create(['codigo' => 'MM', 'country' => 'Birmania']);
        Country::create(['codigo' => 'BO', 'country' => 'Bolivia']);
        Country::create(['codigo' => 'BA', 'country' => 'Bosnia y Herzegovina']);
        Country::create(['codigo' => 'BW', 'country' => 'Botsuana']);
        Country::create(['codigo' => 'BR', 'country' => 'Brasil']);
        Country::create(['codigo' => 'BN', 'country' => 'Brunéi']);
        Country::create(['codigo' => 'BG', 'country' => 'Bulgaria']);
        Country::create(['codigo' => 'BF', 'country' => 'Burkina Faso']);
        Country::create(['codigo' => 'BI', 'country' => 'Burundi']);
        Country::create(['codigo' => 'CV', 'country' => 'Cabo Verde']);
        Country::create(['codigo' => 'KH', 'country' => 'Camboya']);
        Country::create(['codigo' => 'CM', 'country' => 'Camerún']);
        Country::create(['codigo' => 'CA', 'country' => 'Canadá']);
        Country::create(['codigo' => 'TD', 'country' => 'Chad']);
        Country::create(['codigo' => 'CL', 'country' => 'Chile']);
        Country::create(['codigo' => 'CN', 'country' => 'China']);
        Country::create(['codigo' => 'CY', 'country' => 'Chipre']);
        Country::create(['codigo' => 'VA', 'country' => 'Ciudad del Vaticano']);
        Country::create(['codigo' => 'CO', 'country' => 'Colombia']);
        Country::create(['codigo' => 'KM', 'country' => 'Comoras']);
        Country::create(['codigo' => 'CG', 'country' => 'Congo']);
        Country::create(['codigo' => 'CD', 'country' => 'Congo']);
        Country::create(['codigo' => 'KP', 'country' => 'Corea del Norte']);
        Country::create(['codigo' => 'KR', 'country' => 'Corea del Sur']);
        Country::create(['codigo' => 'CI', 'country' => 'Costa de Marfil']);
        Country::create(['codigo' => 'CR', 'country' => 'Costa Rica']);
        Country::create(['codigo' => 'HR', 'country' => 'Croacia']);
        Country::create(['codigo' => 'CU', 'country' => 'Cuba']);
        Country::create(['codigo' => 'CW', 'country' => 'Curacao']);
        Country::create(['codigo' => 'DK', 'country' => 'Dinamarca']);
        Country::create(['codigo' => 'DM', 'country' => 'Dominica']);
        Country::create(['codigo' => 'EC', 'country' => 'Ecuador']);
        Country::create(['codigo' => 'EG', 'country' => 'Egipto']);
        Country::create(['codigo' => 'SV', 'country' => 'El Salvador']);
        Country::create(['codigo' => 'AE', 'country' => 'Emiratos Árabes Unidos']);
        Country::create(['codigo' => 'ER', 'country' => 'Eritrea']);
        Country::create(['codigo' => 'SK', 'country' => 'Eslovaquia']);
        Country::create(['codigo' => 'SI', 'country' => 'Eslovenia']);
        Country::create(['codigo' => 'ES', 'country' => 'España']);
        Country::create(['codigo' => 'US', 'country' => 'Estados Unidos de América']);
        Country::create(['codigo' => 'EE', 'country' => 'Estonia']);
        Country::create(['codigo' => 'ET', 'country' => 'Etiopía']);
        Country::create(['codigo' => 'PH', 'country' => 'Filipinas']);
        Country::create(['codigo' => 'FI', 'country' => 'Finlandia']);
        Country::create(['codigo' => 'FJ', 'country' => 'Fiyi']);
        Country::create(['codigo' => 'FR', 'country' => 'Francia']);
        Country::create(['codigo' => 'GA', 'country' => 'Gabón']);
        Country::create(['codigo' => 'GE', 'country' => 'Georgia']);
        Country::create(['codigo' => 'GH', 'country' => 'Ghana']);
        Country::create(['codigo' => 'GI', 'country' => 'Gibraltar']);
        Country::create(['codigo' => 'GD', 'country' => 'Granada']);
        Country::create(['codigo' => 'GR', 'country' => 'Grecia']);
        Country::create(['codigo' => 'GL', 'country' => 'Groenlandi a']);
        Country::create(['codigo' => 'GP', 'country' => 'Guadalupe']);
        Country::create(['codigo' => 'GU', 'country' => 'Guam']);
        Country::create(['codigo' => 'GT', 'country' => 'Guatemala']);
        Country::create(['codigo' => 'GF', 'country' => 'Guayana Francesa']);
        Country::create(['codigo' => 'GG', 'country' => 'Guernsey']);
        Country::create(['codigo' => 'GN', 'country' => 'Guinea']);
        Country::create(['codigo' => 'GQ', 'country' => 'Guinea Ecuatorial']);
        Country::create(['codigo' => 'GW', 'country' => 'Guinea- Bissau']);
        Country::create(['codigo' => 'GY', 'country' => 'Guyana']);
        Country::create(['codigo' => 'HT', 'country' => 'Haití']);
        Country::create(['codigo' => 'HN', 'country' => 'Honduras']);
        Country::create(['codigo' => 'HK', 'country' => 'Hong Kong']);
        Country::create(['codigo' => 'HU', 'country' => 'Hungría']);
        Country::create(['codigo' => 'IN', 'country' => 'India']);
        Country::create(['codigo' => 'ID', 'country' => 'Indonesia']);
        Country::create(['codigo' => 'IR', 'country' => 'Irán']);
        Country::create(['codigo' => 'IQ', 'country' => 'Irak']);
        Country::create(['codigo' => 'IE', 'country' => 'Irlanda']);
        Country::create(['codigo' => 'BV', 'country' => 'Isla Bouvet']);
        Country::create(['codigo' => 'IM', 'country' => 'Isla de Man']);
        Country::create(['codigo' => 'CX', 'country' => 'Isla de Navidad']);
        Country::create(['codigo' => 'NF', 'country' => 'Isla Norfolk']);
        Country::create(['codigo' => 'IS', 'country' => 'Islandia']);
        Country::create(['codigo' => 'BM', 'country' => 'Islas Bermudas']);
        Country::create(['codigo' => 'KY', 'country' => 'Islas Caimán']);
        Country::create(['codigo' => 'CC', 'country' => 'Islas Cocos (Keeling)']);
        Country::create(['codigo' => 'CK', 'country' => 'Islas Cook']);
        Country::create(['codigo' => 'AX', 'country' => 'Islas de Åland']);
        Country::create(['codigo' => 'FO', 'country' => 'Islas Feroe']);
        Country::create(['codigo' => 'GS', 'country' => 'Islas Georgias del Sur y Sandwich del Sur']);
        Country::create(['codigo' => 'HM', 'country' => 'Islas Heard y McDonald']);
        Country::create(['codigo' => 'MV', 'country' => 'Islas Maldivas']);
        Country::create(['codigo' => 'FK', 'country' => 'Islas Malvinas']);
        Country::create(['codigo' => 'MP', 'country' => 'Islas Marianas del Norte']);
        Country::create(['codigo' => 'MH', 'country' => 'Islas Marshall']);
        Country::create(['codigo' => 'PN', 'country' => 'Islas Pitcairn']);
        Country::create(['codigo' => 'SB', 'country' => 'Islas Salomón']);
        Country::create(['codigo' => 'TC', 'country' => 'Islas Turcas y Caicos']);
        Country::create(['codigo' => 'UM', 'country' => 'Islas Ultramarinas Menores de Estados Unidos']);
        Country::create(['codigo' => 'VG', 'country' => 'Islas Vírgenes Británicas']);
        Country::create(['codigo' => 'VI', 'country' => 'Islas Vírgenes de los Estados Unidos']);
        Country::create(['codigo' => 'IL', 'country' => 'Israel']);
        Country::create(['codigo' => 'IT', 'country' => 'Italia']);
        Country::create(['codigo' => 'JM', 'country' => 'Jamaica']);
        Country::create(['codigo' => 'JP', 'country' => 'Japón']);
        Country::create(['codigo' => 'JE', 'country' => 'Jersey']);
        Country::create(['codigo' => 'JO', 'country' => 'Jordania']);
        Country::create(['codigo' => 'KZ', 'country' => 'Kazajistán']);
        Country::create(['codigo' => 'KE', 'country' => 'Kenia']);
        Country::create(['codigo' => 'KG', 'country' => 'Kirgizstán']);
        Country::create(['codigo' => 'KI', 'country' => 'Kiribati']);
        Country::create(['codigo' => 'KW', 'country' => 'Kuwait']);
        Country::create(['codigo' => 'LB', 'country' => 'Líbano']);
        Country::create(['codigo' => 'LA', 'country' => 'Laos']);
        Country::create(['codigo' => 'LS', 'country' => 'Lesoto']);
        Country::create(['codigo' => 'LV', 'country' => 'Letonia']);
        Country::create(['codigo' => 'LR', 'country' => 'Liberia']);
        Country::create(['codigo' => 'LY', 'country' => 'Libia']);
        Country::create(['codigo' => 'LI', 'country' => 'Liechtenstein']);
        Country::create(['codigo' => 'LT', 'country' => 'Lituania']);
        Country::create(['codigo' => 'LU', 'country' => 'Luxemburgo']);
        Country::create(['codigo' => 'MX', 'country' => 'México']);
        Country::create(['codigo' => 'MC', 'country' => 'Mónaco']);
        Country::create(['codigo' => 'MO', 'country' => 'Macao']);
        Country::create(['codigo' => 'MK', 'country' => 'Macedônia']);
        Country::create(['codigo' => 'MG', 'country' => 'Madagascar']);
        Country::create(['codigo' => 'MY', 'country' => 'Malasia']);
        Country::create(['codigo' => 'M W', 'country' => 'Malawi']);
        Country::create(['codigo' => 'ML', 'country' => 'Mali']);
        Country::create(['codigo' => 'MT', 'country' => 'Malta']);
        Country::create(['codigo' => 'MA', 'country' => 'Marruecos']);
        Country::create(['codigo' => 'MQ', 'country' => 'Martinica']);
        Country::create(['codigo' => 'MU', 'country' => 'Mauricio']);
        Country::create(['codigo' => 'MR', 'country' => 'Mauritania']);
        Country::create(['codigo' => 'YT', 'country' => 'Mayotte']);
        Country::create(['codigo' => 'FM', 'country' => 'Micronesia']);
        Country::create(['codigo' => 'MD', 'country' => 'Moldavia']);
        Country::create(['codigo' => 'MN', 'country' => 'Mongolia']);
        Country::create(['codigo' => 'ME', 'country' => 'Montenegro']);
        Country::create(['codigo' => 'MS', 'country' => 'Montserrat']);
        Country::create(['codigo' => 'MZ', 'country' => 'Mozambique']);
        Country::create(['codigo' => 'NA', 'country' => 'Namibia']);
        Country::create(['codigo' => 'NR', 'country' => 'Nauru']);
        Country::create(['codigo' => 'NP', 'country' => 'Nepal']);
        Country::create(['codigo' => 'NI', 'country' => 'Nicaragua']);
        Country::create(['codigo' => 'NE', 'country' => 'Níger']);
        Country::create(['codigo' => 'NG', 'country' => 'Nigeria']);
        Country::create(['codigo' => 'NU', 'country' => 'Niue']);
        Country::create(['codigo' => 'NO', 'country' => 'Noruega']);
        Country::create(['codigo' => 'NC', 'country' => 'Nueva Caledonia']);
        Country::create(['codigo' => 'NZ', 'country' => 'Nueva Zelanda']);
        Country::create(['codigo' => 'NL', 'country' => 'Países Bajos']);
        Country::create(['codigo' => 'PK', 'country' => 'Pakistán']);
        Country::create(['codigo' => 'PW', 'country' => 'Palau']);
        Country::create(['codigo' => 'PS', 'country' => 'Palestina']);
        Country::create(['codigo' => 'PA', 'country' => 'Panamá']);
        Country::create(['codigo' => 'PG', 'country' => 'Papúa Nueva Guinea']);
        Country::create(['codigo' => 'PY', 'country' => 'Paraguay']);
        Country::create(['codigo' => 'PE', 'country' => 'Perú']);
        Country::create(['codigo' => 'PF', 'country' => 'Polinesia Francesa']);
        Country::create(['codigo' => 'PL', 'country' => 'Polonia']);
        Country::create(['codigo' => 'PT', 'country' => 'Portugal']);
        Country::create(['codigo' => 'PR', 'country' => 'Puerto Rico']);
        Country::create(['codigo' => 'QA', 'country' => 'Qatar']);
        Country::create(['codigo' => 'GB', 'country' => 'Reino Unido']);
        Country::create(['codigo' => 'CF', 'country' => 'República Centroafrica na']);
        Country::create(['codigo' => 'CZ', 'country' => 'República Checa']);
        Country::create(['codigo' => 'DO', 'country' => 'República Dominicana']);
        Country::create(['codigo' => 'RE', 'country' => 'Reunión']);
        Country::create(['codigo' => 'RW', 'country' => 'Ruanda']);
        Country::create(['codigo' => 'RO', 'country' => 'Rumanía']);
        Country::create(['codigo' => 'RU', 'country' => 'Rusia']);
        Country::create(['codigo' => 'EH', 'country' => 'Sahara Occidental']);
        Country::create(['codigo' => 'WS', 'country' => 'Samoa']);
        Country::create(['codigo' => 'AS', 'country' => 'Samoa Americana']);
        Country::create(['codigo' => 'BL', 'country' => 'San Bartolomé']);
        Country::create(['codigo' => 'KN', 'country' => 'San Cristóbal y Nieves']);
        Country::create(['codigo' => 'SM', 'country' => 'San Marino']);
        Country::create(['codigo' => 'MF', 'country' => 'San Martín Francesa']);
        Country::create(['codigo' => 'PM', 'country' => 'San Pedro y Miquelón']);
        Country::create(['codigo' => 'VC', 'country' => 'San Vicente y las Granadinas']);
        Country::create(['codigo' => 'SH', 'country' => 'Santa Elena']);
        Country::create(['codigo' => 'LC', 'country' => 'Santa Lucía']);
        Country::create(['codigo' => 'ST', 'country' => 'Santo Tomé y Príncipe']);
        Country::create(['codigo' => 'SN', 'country' => 'Senegal']);
        Country::create(['codigo' => 'RS', 'country' => 'Serbia']);
        Country::create(['codigo' => 'SC', 'country' => 'Seychelles']);
        Country::create(['codigo' => 'SL', 'country' => 'Sierra Leona']);
        Country::create(['codigo' => 'SG', 'country' => 'Singapur']);
        Country::create(['codigo' => 'SX', 'country' => 'Sint Maarten Holandesa']);
        Country::create(['codigo' => 'SY', 'country' => 'Siria']);
        Country::create(['codigo' => 'SO', 'country' => 'Somalia']);
        Country::create(['codigo' => 'LK', 'country' => 'Sri Lanka']);
        Country::create(['codigo' => 'ZA', 'country' => 'Sudáfrica']);
        Country::create(['codigo' => 'SD', 'country' => 'Sudán']);
        Country::create(['codigo' => 'SE', 'country' => 'Suecia']);
        Country::create(['codigo' => 'CH', 'country' => 'Suiza']);
        Country::create(['codigo' => 'SR', 'country' => 'Surinam']);
        Country::create(['codigo' => 'SJ', 'country' => 'Svalbard y Jan Mayen']);
        Country::create(['codigo' => 'SZ', 'country' => 'Suazilandia']);
        Country::create(['codigo' => 'TH', 'country' => 'Tailandia']);
        Country::create(['codigo' => 'TW', 'country' => 'Taiwán']);
        Country::create(['codigo' => 'TZ', 'country' => 'Tanzania']);
        Country::create(['codigo' => 'IO', 'country' => 'Territorio Británico del Océano Índico']);
        Country::create(['codigo' => 'TF', 'country' => 'Territorios Australes y Antárticas Franceses']);
        Country::create(['codigo' => 'TL', 'country' => 'Timor Oriental']);
        Country::create(['codigo' => 'TG', 'country' => 'Togo']);
        Country::create(['codigo' => 'TK', 'country' => 'Tokelau']);
        Country::create(['codigo' => 'TO', 'country' => 'Tonga']);
        Country::create(['codigo' => 'TT', 'country' => 'Trinidad y Tobago']);
        Country::create(['codigo' => 'TN', 'country' => 'Túnez']);
        Country::create(['codigo' => 'TM', 'country' => 'Turkmenistán']);
        Country::create(['codigo' => 'TR', 'country' => 'Turquía']);
        Country::create(['codigo' => 'TV', 'country' => 'Tuvalu']);
        Country::create(['codigo' => 'UA', 'country' => 'Ucrania']);
        Country::create(['codigo' => 'UG', 'country' => 'Uganda']);
        Country::create(['codigo' => 'UY', 'country' => 'Uruguay']);
        Country::create(['codigo' => 'UZ', 'country' => 'Uzbekistán']);
        Country::create(['codigo' => 'VU', 'country' => 'Vanuatu']);
        Country::create(['codigo' => 'VE', 'country' => 'Venezuela']);
        Country::create(['codigo' => 'VN', 'country' => 'Vietnam']);
        Country::create(['codigo' => 'WF', 'country' => 'Wallis y Futuna']);
        Country::create(['codigo' => 'YE', 'country' => 'Yemen']);
        Country::create(['codigo' => 'DJ', 'country' => 'Yibuti']);
        Country::create(['codigo' => 'ZM', 'country' => 'Zambia']);
        Country::create(['codigo' => 'ZW', 'country' => 'Zimbabue']);
        Country::create(['codigo' => 'ZZ', 'country' => 'Otro']);

    }
}
